# Generated by Django 4.0.1 on 2022-11-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmci_app', '0002_djangotestcompo_delete_compo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoTestMain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quatation_meta_id', models.CharField(max_length=100)),
                ('quatation_subject', models.TextField(blank=True, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reserve_num', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('quataion_total', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_test_main',
                'managed': False,
            },
        ),
    ]
